### ISSUE TITLE
Airspy HF+ Discovery

### ISSUE THREAD

**Issue by dupilax** [pothosware/SoapyAirspyHF#10]
Hi

Will SoapyAirspyHF be compatible as-is with the new Airspy HF+ Discovery ?

Thanks

**Comment by ast** [comment]
I asked the creator of the Airspys on Twitter and he says the Discovery
also uses libairspyhf so it's completely compatible in that respect.

Should probably work without any modifications.


--Albin

**Comment by dupilax** [comment]
that's a very good news, thanks !
