### ISSUE TITLE
Trouble compiling on Ubuntu

### ISSUE THREAD

**Issue by wx273** [pothosware/SoapyAirspyHF#15]
I'm trying to compile this to use a AirSpyHF+ Discovery with rx_fm.
The device is recognised with just the AirSpy driver with gqrx but the HF+ Discovery apparently needs this driver for rx_tools. It seems to be missing the include libraries but I'm stumped how to solve this.
I followed the Pothos Soapy build instructions and they completed without error. I have the hwe kernel.
Any ideas what I can do please ?

git clone https://github.com/pothosware/SoapyAirspyHF.git
Cloning into 'SoapyAirspyHF'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 85 (delta 4), reused 10 (delta 4), pack-reused 73
Unpacking objects: 100% (85/85), done.

cd SoapyAirspyHF/
mkdir build
cd build
cmake ..
-- The CXX compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type not specified: defaulting to release.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'libairspyhf'
--   No package 'libairspyhf' found
-- Could NOT find LIBAIRSPYHF (missing: LIBAIRSPYHF_LIBRARIES LIBAIRSPYHF_INCLUDE_DIRS) 
-- Performing Test HAS_STD_CXX11
-- Performing Test HAS_STD_CXX11 - Success
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- Module airspyhfSupport configured with version: 0.1.1-54f5487
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBAIRSPYHF_INCLUDE_DIRS (ADVANCED)
   used as include directory in directory /home/user1/code/SoapyAirspyHF
   used as include directory in directory /home/user1/code/SoapyAirspyHF
   used as include directory in directory /home/user1/code/SoapyAirspyHF
   used as include directory in directory /home/user1/code/SoapyAirspyHF
   used as include directory in directory /home/user1/code/SoapyAirspyHF
   used as include directory in directory /home/user1/code/SoapyAirspyHF
   used as include directory in directory /home/user1/code/SoapyAirspyHF
LIBAIRSPYHF_LIBRARIES (ADVANCED)
    linked by target "airspyhfSupport" in directory /home/user1/code/SoapyAirspyHF

-- Configuring incomplete, errors occurred!
See also "/home/user1/code/SoapyAirspyHF/build/CMakeFiles/CMakeOutput.log".

Linux meteor-test 5.0.0-36-generic #39~18.04.1-Ubuntu SMP Tue Nov 12 11:09:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by guruofquality** [comment]
You need to install libairspyhf to build this project- https://github.com/pothosware/SoapyAirspyHF/wiki#dependencies

**Comment by wx273** [comment]
Yes ! That was it.
I had done that previously but then switched laptops and this one didn't have it on there.
Thank you very much !!! :)
