### ISSUE TITLE
Setting stream to CF32

### ISSUE THREAD

**Issue by wx273** [pothosware/SoapyAirspyHF#16]
No sure where to ask this one, here or SoapySDR or rx_tools...
AirspyHF+ Disco is now recognised by soapy but rx_fm fails with a stream format error :

rx_fm -d 0 -M wbfm -f 89.5M -F CF32 | sox -r 32k -t raw -e s -b 16 -c 1 - -d
sox WARN alsa: can't encode 0-bit Unknown or not applicable
Using device AirspyHF: serial=c852fd808b2f4a3b 
Found 1 channel(s) :
Channel 0 :
  Found 1 antenna(s): RX 
  Found 2 gain(s): LNA RF 
  Found 1 frequencies: RF 
  Found 4 sample rates: 768000 384000 256000 192000 
  Found 0 bandwidths: 
SoapySDRDevice_setupStream failed: setupStream invalid format 'CS16' -- Only CF32 is supported by SoapyAirspyHF module.
Bandwidth set to automatic resulted in 0 Hz.
Tuned to 89856000 Hz.
Oversampling input by: 8x.
Oversampling output by: 1x.
Buffer size: 6.02ms
Sampling at 1360000 S/s.
Output at 170000 Hz.

-: (raw)

 File Size: 0         
  Encoding: Signed PCM    
  Channels: 1 @ 16-bit   
Samplerate: 32000Hz      
Replaygain: off         
  Duration: unknown      

In:0.00% 00:00:00.00 [00:00:00.00] Out:0     [      |      ]        Clip:0    
Done.

It seems to be not auto-setting the stream rate for this device type to the only one it supports and I can't seem to force it with -F CF32.

SoapySDRUtil --probe
######################################################
######################################################

Probe device 

----------------------------------------------------
-- Device identification
----------------------------------------------------
  driver=AirspyHF
  hardware=AirspyHF
  serial=c852fd808b2f4a3b

----------------------------------------------------
-- Peripheral summary
----------------------------------------------------
  Channels: 1 Rx, 0 Tx
  Timestamps: NO

----------------------------------------------------
-- RX Channel 0
----------------------------------------------------
  Full-duplex: YES
  Supports AGC: YES
  Stream formats: CF32
  Native format: CF32 [full-scale=1]
  Antennas: RX
  Full gain range: [0, 54] dB
    LNA gain range: [0, 6, 6] dB
    RF gain range: [-48, 0, 6] dB
  Full freq range: [0.009, 31], [60, 260] MHz
    RF freq range: [0.009, 31], [60, 260] MHz
  Sample rates: 0.768, 0.384, 0.256, 0.192 MSps

Am I doing something obviously wrong ?
Thanks

**Comment by guruofquality** [comment]
There is already an open issue for this: https://github.com/pothosware/SoapyAirspyHF/issues/5

I am hoping that someone with airspyhf will be able to contribute a pull request :-)
