### ISSUE TITLE
timeout error since firmware 2.0.0

### ISSUE THREAD

**Issue by dupilax** [pothosware/SoapyAirspyHF#8]
Hello

I get lot of error timeout during the day with new firmware 2.0.0 (was 1.0.0 before)
Same Raspberry PI with same power supply, not overloaded.

Here is a log in daemon.log : 
SoapySDR device 'driver=airspyhf,device_id=0': readStream failed: TIMEOUT, disabling

Any clue to debug this ?

Thanks

**Comment by jazzkutya** [comment]
that's interesting, I got similar results but I thought this was due to the gain settings I added to this project but I also upgraded fw from 1.0 to latest 1.x so maybe real cause is the firmware. which exact version of airspyhf are you using?

**Comment by jazzkutya** [comment]
also in my experience this timeout only happens at start of stream and when setting agc on/off later while streaming

**Comment by jazzkutya** [comment]
what program produced that log message?

**Comment by dupilax** [comment]
it it rtl_airband

it happens for an hour and half after launching rtl_airband and not changing gain or AGC

maybe downgrading to firmware 1.0.0 worth a try ?

**Comment by jazzkutya** [comment]
don't forget if you downgrade you reintroduce the firmware upgrade bug. what version or which commit of SoapyAirspyHF are you using?

**Comment by dupilax** [comment]
Yes I have to keep a screwdriver nearby... ;-)
there is new option to change the gain in rtl_airband. I will try today with AGC as before

SoapySDRUtil --info
######################################################
##     Soapy SDR -- the SDR abstraction library     ##
######################################################

Lib Version: v0.8.0-gac770377
API Version: v0.8.0
ABI Version: v0.8

**Comment by dupilax** [comment]
SoapyAirspyHF : last version with git pull

**Comment by jazzkutya** [comment]
ok, don't change the firmware yet. I will update this comment with a link to download earlier version or SoapyAirspyHF and please try that one

**Comment by dupilax** [comment]
firmware 2.0.0 
SoapyAirSpyHF  last version installed
just launch rtl_airband with AGC, 
keep you posted
thanks a lot

**Comment by dupilax** [comment]
No problem so far.

And AirSpy HF+ definitely worth it !

Thanks a lot

Best regards

Philippe

**Comment by dupilax** [comment]
too bad...
SoapySDR device 'driver=airspyhf,device_id=0': readStream failed: TIMEOUT, disabling

firmware downgrade ?

**Comment by jazzkutya** [comment]
Have you tried the earlier SoapyAirspyhf version I mentioned above with a download link?

**Comment by dupilax** [comment]
yes this is the one i installed before the test

**Comment by jazzkutya** [comment]
thanks, that means the problem exists even with the earlier SoapyAirSpyHF, the one that does not support gain settings. You could try to convince the developers or rtl_airband to ignore timeouts or revert back to old firmware but I don't like that option, for me gain settings are a must :)

**Comment by jazzkutya** [comment]
R2.2.0 - 2019-06-04  Better underrun/overrun handling.
this might be just the firmware update you are looking for

**Comment by dupilax** [comment]
Oh yes maybe !

Sadly I can’t upgrade till saturday.
I keep you posted !

Thanks a lot

**Comment by dupilax** [comment]
You're right, this is the needed firmware version !
No timeout since 6 hours...
Thanks a lot

**Comment by jazzkutya** [comment]
thank you for the feedback, can you close this issue please?
